### PR TITLE
Hotel-Website

### PR DESCRIPTION
**Pull request by Gimbalgal**
Hello good day, I hope this mail finds you well. 

I have been responsible for designing a hotel website from scratch using a design provided for me in Figma. I made use of HTML, CSS, and JavaScript. After all the hassles, I present my design to you with great delight. 

Attached is my pull request link for your review and comment.

Thank you, 

Victoria Augustine Ishabo.

### CODE REVIEW

**Review by Xfarouq — CHANGES_REQUESTED** [review]
Hi @Gimbalgal 

Good job so far!
You still need to work on some issues to get your project approved, but you are almost there!

<div style="text-align:center;">
    Remote Collaboration
</div>

### To Highlight 💯
- **Clean code** 👍
- **Good use of Gitflow** 👍
- **Implemented some project requirements** 👍

### Required Changes ♻️

- Make your Pull Request Title and Description to be more professional
- Try tp make your hamburger menu when clicked to take the full height of your website and to make it non scrollable

### Optional Suggestions
Every comment with the `[OPTIONAL]` prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding! 👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.  
Please, remember to tag me in your question so I can receive the notification._

**Review by Xfarouq — CHANGES_REQUESTED** [review]
Hi @Gimbalgal 

Good job so far!
You still need to work on some issues to get your project approved, but you are almost there!

<div style="text-align:center;">
    Remote Collaboration
</div>

### To Highlight 💯
- **Clean code** 👍
- **Good use of Gitflow** 👍
- **Implemented some project requirements** 👍

### Required Changes ♻️
- The title should be something like Hotel Mobile Website and your description is okay but saying your from module 2 and stuffs isn't necessary but the rest if the description is okay.

- And you haven't done corrections of the hamburger menu to make the hamburger menu take the full height and make it non scrollable when clicked 
- Or is it that you have implemented the hamburger corrections but you haven't updated the demo link?
- P.S you are to always updated your demo link in your readme with each changes made

### Optional Suggestions
Every comment with the `[OPTIONAL]` prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding! 👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.  
Please, remember to tag me in your question so I can receive the notification._

**Comment by Gimbalgal** [comment]
Hello Sir, I understood the part of hamburger menu taken the height but I
don't understand the non scrollable when click.

I will appreciate more clarity.

Thank you.

**Comment by Xfarouq** [comment]
- You stil haven't corrected the Pull Request Title check the image below and rectify it please
image

- For making the hamburger menu non scrollable please check the link below for more understanding
https://hotel-web-app-edq3.onrender.com/

After you have implemented all changes then resubmit your project as the 3rd review again

**Comment by Xfarouq** [comment]
Also remove all the commented html in your code that you rendered using javascript

**Review by Xfarouq — APPROVED** [review]
Hi @Gimbalgal 

Your project is complete! There is nothing else to say other than... it's time to merge it!!!
Congratulations! 🎉

<div style="text-align:center;">
    Remote Collaboration
</div>

### Highlights
- ✅ **Professional Readme**
- ✅ **Good use of Gitflow**
- ✅ **UI looks like the Figma design**
- ✅ **Good use of HTML semantics**
- ✅ **Professional commit messages**
- ✅ **Professional PR title**
- ✅ **Professional PR description**

### Optional Suggestions

- Make sure to remove the commented html which was rendered using html
Every comment with the `[OPTIONAL]` prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding! 👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.  
Please, remember to tag me in your question so I can receive the notification._

**Pull request merged**
